# Generated by Django 4.0.4 on 2022-05-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('ano_letivo', models.CharField(max_length=10)),
                ('topicos', models.TextField()),
                ('ranking', models.IntegerField()),
                ('pagina_cadeira', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('link1', models.CharField(max_length=300)),
                ('link2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('ano_realizacao', models.IntegerField()),
                ('link_github', models.CharField(max_length=300)),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira')),
                ('participantes', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
    ]
