# Generated by Django 4.0.4 on 2022-05-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_escola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
