# Generated by Django 4.0.4 on 2022-05-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='linguagem',
            name='tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
