# Generated by Django 4.0.4 on 2022-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='link',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
