# Generated by Django 4.0.4 on 2022-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_escola_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
