# Generated by Django 4.0.4 on 2022-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_interesse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='linguagem',
            name='image',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
