# Generated by Django 4.0.4 on 2022-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_linguagem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
