# Generated by Django 4.0.4 on 2022-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=60)),
                ('pergunta1', models.CharField(max_length=60)),
                ('pergunta2', models.CharField(max_length=60)),
                ('pergunta3', models.CharField(max_length=60)),
                ('pergunta4', models.CharField(max_length=60)),
                ('pergunta5', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='uploads/')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='descricao',
        ),
    ]
