# Generated by Django 4.0.4 on 2022-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_quiz_rede_remove_post_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta5',
        ),
        migrations.AddField(
            model_name='quiz',
            name='opcao1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='opcao2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='opcao3',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='opcao4',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='pergunta',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='resposta',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
