# Generated by Django 4.0.4 on 2022-06-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_quiz_pergunta1_remove_quiz_pergunta2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='uploads/')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='opcao1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='opcao2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='opcao3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='opcao4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='resposta',
        ),
        migrations.AddField(
            model_name='quiz',
            name='pergunta1',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='pergunta2',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='pergunta3',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='pergunta4',
            field=models.CharField(default=11, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='pergunta5',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
