# Generated by Django 4.0.4 on 2022-06-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_noticia_remove_quiz_opcao1_remove_quiz_opcao2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='nome_pessoa',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pergunta5',
        ),
    ]
