# Generated by Django 4.0.4 on 2022-06-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_rename_nome_pessoa_quiz_nome_remove_quiz_pergunta1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pontuacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
