# Generated by Django 4.0.5 on 2022-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_quiz_pontuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.TextField(max_length=500)),
                ('ano_realizacao', models.IntegerField()),
                ('image', models.FileField(upload_to='uploads/')),
                ('link_github', models.CharField(max_length=300)),
                ('link_vídeo', models.CharField(max_length=300)),
                ('autores', models.ManyToManyField(related_name='autores', to='portfolio.pessoa')),
                ('orientadores', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
    ]
