# Generated by Django 4.0.5 on 2022-06-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_tfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfc',
            name='link_vídeo',
        ),
        migrations.AlterField(
            model_name='tfc',
            name='resumo',
            field=models.TextField(max_length=800),
        ),
    ]
